name: Build

on:
  push:
    branches:
      - master
      - develop

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Hadolint Action Dockerfile.alpine
        uses: brpaz/hadolint-action@v1.1.0
        with:
          dockerfile: Dockerfile.alpine

      - name: Hadolint Action Dockerfile.alpine.mongo
        uses: brpaz/hadolint-action@v1.1.0
        with:
          dockerfile: Dockerfile.alpine.mongo

      - name: Hadolint Action Dockerfile.alpine.mongo
        uses: brpaz/hadolint-action@v1.1.0
        with:
          dockerfile: Dockerfile.alpine.mongo

      - name: Hadolint Action Dockerfile.debian
        uses: brpaz/hadolint-action@v1.1.0
        with:
          dockerfile: Dockerfile.debian.nomongo

      - name: Install Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest

      - name: hub.docker.com Login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build the multi-arch image
        run: |
          docker buildx build \
            --push \
            --tag tty0/isp_telegraf:1.15.3 \
            --tag tty0/isp_telegraf:latest \
            --platform linux/amd64,linux/arm/v7,linux/arm64 ./docker-compose/telegraf/

